# Generated by Django 5.2.8 on 2025-11-24 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_experience', models.CharField(choices=[('0', 'No experience required'), ('1', '1 year of experience required'), ('2', '2 years of experience required'), ('3', '3 years of experience required'), ('4', '4 years of experience required'), ('5', '5 or more years of experience required')], max_length=1)),
                ('application_date', models.DateTimeField()),
                ('response_date', models.DateField()),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('PROCESS', 'In Process'), ('REJ_REV', 'Rejected after review'), ('REJ_DIR', 'Directly Rejected')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.company')),
            ],
        ),
    ]
