# Generated by Django 5.2.8 on 2025-12-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
