# Generated by Django 4.2.27 on 2025-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(help_text='Tareas, certificaciones, requisitos...', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='application',
            name='location',
            field=models.CharField(help_text='Madrid, Barcelona...', max_length=100, verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='application',
            name='required_experience',
            field=models.CharField(choices=[('0', 'Sin experiencia'), ('1', '1 año'), ('2', '2 años'), ('3', '3 años'), ('4', '4 años'), ('5', '5 años'), ('6', 'No especificado')], max_length=1, verbose_name='Experiencia requerida'),
        ),
        migrations.AlterField(
            model_name='application',
            name='response_date',
            field=models.DateField(blank=True, help_text='Fecha de respuesta', null=True, verbose_name='Fecha de respuesta'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Solicitado'), ('PROCESS', 'En proceso'), ('REJ_REV', 'Rechazo tras entrevista'), ('REJ_DIR', 'Rechazo directo')], max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(help_text='Ej: Desarrollador Backend Python', max_length=200, verbose_name='Título del puesto'),
        ),
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.URLField(help_text='Enlace a la oferta', verbose_name='URL'),
        ),
    ]
